import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="py-5 px-10 bg-[#FFDA5F] text-xl flex flex-row justify-between">
          <div>
            <a href="/" className="font-[Samarkan] text-3xl">
              Truck Mitra
            </a>
            <span className="ml-3">Admin Panel</span>
          </div>
          <a href="/agency">Account</a>
        </nav>
        <main className="p-5">{children}</main>
      </body>
    </html>
  );
}
